### ISSUE TITLE
New json Failed error - How can we help?

### ISSUE THREAD

**Issue by zackat3dmedia** [Haroon96/warzone-stats#89]
Here is the error I received requesting !wz stats rsg 5h

Failed to fetch stats!
invalid json response body at https://api.tracker.gg/api/v2/warzone/standard/matches/atvi/green%20kilo%200725%236587584?type=wz&next=null reason: Unexpected token < in JSON at position 0
Retry 2 of 5

**Comment by osama-h-rana** [comment]
Hi, we're aware of the issue and are trying to fix it. :)

**Comment by Haroon96** [comment]
Fixed with an internal redeployment. 

The cod.tracker.gg API has been bugging us quite a bit recently. Hopefully this fix lasts otherwise we might have to consider calling it quits. A more permanent solution would require significant refactoring for which none of the developers have time to work on.
