### ISSUE TITLE
An error occurred!

### ISSUE THREAD

**Issue by jee1tha** [Haroon96/warzone-stats#93]
when i try to use the bot, it shows 
'An error occurred!'
Even with the cmd in the wiki :  !wz stats br psn botmun_ 2w

**Comment by l0g4n1337** [comment]
same for me .. seems not working

**Comment by osama-h-rana** [comment]
Sadly, the complications to keep the bot running with changes made to the tracker api mean that we're shutting down the bot for now, especially since we no longer play the game and aren't up to date with what's happening in warzone.

If we come back to the game (perhaps with warzone 2?), we'll try to revive the project. In the meantime, the bot will remain open source for anyone looking to host the bot on their own machines.
